# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0003_auto_20171009_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('document_number', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='cedula')),
                ('phone_number', models.BigIntegerField(verbose_name='número telefónico')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='correo electrónico')),
                ('birthday', models.DateField(null=True, verbose_name='Fecha de Cumpleaños')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'verbose_name': 'Cliente',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('document', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='cédula')),
                ('phone_number', models.CharField(max_length=10, verbose_name='celular')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='correo electrónico')),
            ],
            options={
                'verbose_name_plural': 'Empleados',
                'verbose_name': 'Empleado',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='código')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='nombre')),
                ('price', models.IntegerField(verbose_name='precio')),
                ('amount', models.IntegerField(verbose_name='cantidad')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'verbose_name': 'Producto',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='descripción')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='fecha')),
                ('value', models.IntegerField(verbose_name='valor')),
                ('register_type', models.PositiveSmallIntegerField(choices=[(10, 'ingreso'), (20, 'gasto')], verbose_name='servicio')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Client', verbose_name='cliente')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Employee', verbose_name='propietario')),
            ],
            options={
                'verbose_name_plural': 'Registros',
                'verbose_name': 'Registro',
                'ordering': ['date'],
            },
        ),
    ]
