# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='descripción'),
        ),
    ]
