# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_client_employee_product_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=10, verbose_name='celular'),
        ),
    ]
