# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20171009_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='document_number',
        ),
        migrations.AddField(
            model_name='client',
            name='document',
            field=models.CharField(default=321213321, max_length=30, primary_key=True, serialize=False, verbose_name='cédula'),
            preserve_default=False,
        ),
    ]
