# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20171009_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Client', verbose_name='cliente'),
        ),
    ]
