# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20171020_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='celular'),
        ),
    ]
