# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20171126_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstheticHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True, verbose_name='nombre')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.EstheticHouse', verbose_name='casa estética'),
        ),
    ]
