# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_auto_20171126_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esthetichouse',
            options={'ordering': ['name'], 'verbose_name': 'Casa Estética', 'verbose_name_plural': 'Casas Estéticas'},
        ),
    ]
